I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/prologue.rpy", line 36, in script
    if a == True:
  File "game/script/prologue.rpy", line 36, in <module>
    if a == True:
NameError: name 'a' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/prologue.rpy", line 36, in script
    if a == True:
  File "C:\Users\RENNKA\Desktop\renpy-7.3.5-sdk\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\RENNKA\Desktop\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\RENNKA\Desktop\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script/prologue.rpy", line 36, in <module>
    if a == True:
NameError: name 'a' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
rks 1.0
Tue Feb 04 19:45:06 2020
